### ISSUE TITLE
"Add a Memo" and Memo dialog only visible for Admin Users

### ISSUE THREAD

**Issue by heraldodinero** [gibus/RT-Extension-Memo#3]
My RT SuperUser account is the only account that's able to see the "Add a Memo" button, and the memo data (if a memo was entered for a given ticket).

Am I missing something? Need to be able to add and read memo data for regular "Privileged" users, not only the SuperUser.

**Comment by gibus** [comment]
See section "Rights" in README:

> The following new rights can be applied at the global level or at the queue level:
> * SeeMemo
>     Users and groups with this right are able to see the Memo on the display page of a ticket.
> * ModifyMemo
>     Users and groups with this right are able to add a new Memo and to edit existing Memo attached to a ticket.
