### ISSUE TITLE
Update plugin for RT5

### ISSUE THREAD

**Issue by kylemhall** [gibus/RT-Extension-Memo#4]
Will you be updating the Memo plugin for RT5?

**Comment by mnadai** [comment]
The README.md contains a reference to /opt/rt5.
So I tried adding it to my RT5 (5.0.4) staging environment and it seems to be working ok.

**Comment by gibus** [comment]
Sorry Iv've forgitten to reply to your issue, but yes I've updated this extension to RT5.
